"""Literature Synthesis & Knowledge Extraction Engine.

Compiles findings from academic sources, extracts state-of-the-art baselines,
mathematical formulations, and architectural specifications into .ai-harness/research/findings/.
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import List, Optional
from ai_harness.core.models import ResearchItem
from ai_harness.research.arxiv_client import ArxivClient
from ai_harness.research.crossref_client import CrossRefClient
from ai_harness.storage.checkpoint_manager import CheckpointManager


class ResearchSynthesizer:
    """Orchestrates literature searches across arXiv, CrossRef/IEEE, and synthesizes findings."""

    def __init__(self, checkpoint_mgr: CheckpointManager):
        self.checkpoint_mgr = checkpoint_mgr
        self.arxiv_client = ArxivClient()
        self.crossref_client = CrossRefClient()

    def conduct_deep_research(self, topic: str, max_results_per_source: int = 5) -> List[ResearchItem]:
        """Scrapes research papers across arXiv and CrossRef/IEEE and persists items."""
        found_items: List[ResearchItem] = []

        # 1. Query arXiv
        arxiv_papers = self.arxiv_client.search(topic, max_results=max_results_per_source)
        found_items.extend(arxiv_papers)

        # 2. Query CrossRef (covers IEEE, ACM, Springer)
        crossref_papers = self.crossref_client.search(topic, max_results=max_results_per_source)
        found_items.extend(crossref_papers)

        # 3. Deduplicate by title similarity
        unique_items: List[ResearchItem] = []
        seen_titles = set()
        for item in found_items:
            clean_title = "".join(ch for ch in item.title.lower() if ch.isalnum())
            if clean_title not in seen_titles:
                seen_titles.add(clean_title)
                unique_items.append(item)
                # Persist to .ai-harness/research/
                self.checkpoint_mgr.record_research_source(item)

        # 4. Generate structured synthesis document
        self.generate_synthesis_document(topic, unique_items)

        return unique_items

    def generate_synthesis_document(self, topic: str, papers: List[ResearchItem]) -> Path:
        """Create a structured markdown document summarizing research foundations."""
        date_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        slug = "".join(c if c.isalnum() else "_" for c in topic.lower())[:32]
        filename = f"synthesis_{slug}.md"

        papers_section = []
        for i, p in enumerate(papers, 1):
            authors_str = ", ".join(p.authors[:3]) + (" et al." if len(p.authors) > 3 else "")
            papers_section.append(
                f"""### {i}. {p.title}
- **Source:** `{p.source}` | **Published:** `{p.published_date}`
- **Authors:** {authors_str or 'Anonymous / Institutional'}
- **URL/DOI:** [{p.url}]({p.url})
- **Abstract Summary:** {p.abstract[:350]}...
- **Extracted Findings:**
{chr(10).join([f"  - {f}" for f in p.extracted_key_findings])}
"""
            )

        content = f"""# SOTA Research Synthesis: {topic}

> **Generated by:** AI Autonomous Harness (Agent 2: Research Scout)  
> **Timestamp:** `{date_str}`  
> **Total Papers Analyzed:** {len(papers)} (arXiv, IEEE, CrossRef)  

---

## 1. Executive Research Overview
This research artifact provides state-of-the-art foundational analysis for **{topic}**.
It serves as the technical ground-truth for the V-Model left-wing (Architecture and Detailed Design),
ensuring our implementation adopts validated mathematical models, verified algorithms, and standard benchmarks.

---

## 2. Analyzed Academic Papers & Publications

{chr(10).join(papers_section) if papers_section else "_No academic papers retrieved for this query._"}

---

## 3. Algorithmic Recommendations & Invariants for SDLC
1. **Mathematical Grounding:** Ensure critical formulas (e.g. flow ratios, cost functions, latency bounds) are directly derived from peer-reviewed literature.
2. **Deterministic Fallbacks:** When non-deterministic or ML models are used, establish a hard-coded deterministic baseline (e.g., Webster's ATSC or heuristic queue balancer) for safety gating.
3. **Reproducibility:** Capture input distributions, random seeds, and benchmark evaluation metrics in all QA/verification test suites.
"""
        return self.checkpoint_mgr.save_research_finding(filename, content)
